### ISSUE TITLE
Login with username and password doesn't work

### ISSUE THREAD

**Issue by pythoncat1** [DarkCat09/python-aternos#105]
Logging in with username and password doesn't work. However session id login in does.

**Comment by DarkCat09** [comment]
Duplicate of #97

**Comment by DarkCat09** [comment]
Fixed, but new version was not released

**Comment by pythoncat1** [comment]
Thanks!

**Comment by pythoncat1** [comment]
@DarkCat09 updating to the latest version with pip doesn't fix this issue. I'll just install it from the source, but just pointing this out.

**Comment by DarkCat09** [comment]
@pythoncat1, yeah, I'll update it someday...

Anyway, thanks for reporting the bug.
