### ISSUE TITLE
Detected a Cloudflare version 2 Captcha challenge

### ISSUE THREAD

**Issue by siroo2137** [DarkCat09/python-aternos#52]
error:
`cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.`

**Comment by DarkCat09** [comment]
Could you provide more information:
1. What version of python-aternos have you installed?
2. On which device do you use this library (your PC or VPS like Repl.it)?
3. If it's your computer, where do you live (USA, Europe, Russia or China/Japan)?

**Comment by DarkCat09** [comment]
I checked the latest version (1.1.2) on Repl.it and my PC. It works properly.  
To reproduce the error, I need to connect to VPN or test python-aternos on other python hostings.

**Comment by DarkCat09** [comment]
Anyway, the problem is in cloudscraper library.

You can try installing python-aternos in the [development mode](https://python-aternos.codeberg.page/#development) and adding to the 202th line in `atconnect.py` these parameters to CloudScraper constructor:
```python
self.session = CloudScarper(
    browser='chrome'
)
```

If these changes didn't help, install [Node.js](https://nodejs.org/) and use it in CloudScraper:
```python
self.session = CloudScarper(
    interpreter='nodejs'
)

# And also try

self.session = CloudScraper(
    interpreter='nodejs',
    browser='chrome'
)
```

**Comment by siroo2137** [comment]
ok thanks for help, i'll try that out

**Comment by siroo2137** [comment]
> Could you provide more information:
> 
> 1. What version of python-aternos have you installed?
> 2. On which device do you use this module (your PC or VPS like Repl.it)?
> 3. If it's your computer, where do you live (USA, Europe, Russia or China/Japan)?

1. i installed python-aternos via pip (pip install python-aternos) and the version is i think 2.0.1
2. i use the module on my pc
3. i live in poland

**Comment by siroo2137** [comment]
> Anyway, the problem is in cloudscraper library.
> 
> You can try installing python-aternos in the [development mode](https://python-aternos.codeberg.page/#development) and adding to the 202th line in `atconnect.py` these parameters to CloudScraper constructor:
> 
> ```python
> self.session = CloudScarper(
>     browser='chrome'
> )
> ```
> 
> If these changes didn't help, install [Node.js](https://nodejs.org/) and use it in CloudScraper:
> 
> ```python
> self.session = CloudScarper(
>     interpreter='nodejs'
> )
> 
> # And also try
> 
> self.session = CloudScraper(
>     interpreter='nodejs',
>     browser='chrome'
> )
> ```
 and after doing this (installing python-aternos in development mode and changing the line 202 to ```self.session = CloudScarper(
     browser='chrome'
 )```
it still displays the same error

**Comment by siroo2137** [comment]
i'll reply after i check is it working on my ubuntu vps (in germany)

**Comment by reka7490** [comment]
> same here i changed the line 202 and still get the same error

everything is exactly the same for me

**Comment by DarkCat09** [comment]
@siroo2137, @BABAROKA911, @reka7490,

This error means that Cloudflare responses with [hCaptcha](https://www.hcaptcha.com/) which cloudscraper cannot pass.

You can use [services](https://github.com/venomous/cloudscraper#3rd-party-captcha-solvers) like 2captcha or automated captcha solvers based on machine learning.

I'll implement captcha solving through the 1st way (paid services) soon.

**Comment by DarkCat09** [comment]
Please, update to the latest version:
```python
pip install -U "python-aternos>=2.1.1"
```

Here's how to add a captcha solver API key:
```python
from python_aternos import Client

at = Client.from_credentials(
    'username',
    'password',
    captcha={
        'provider': '2captcha',
        'api_key': 'your_api_key',
    }
)
```

All available captcha solvers you can find [here](https://github.com/VeNoMouS/cloudscraper#3rd-party-captcha-solvers).  
Just copy "capctha={...}" from this page and paste to the code below.

**Comment by DarkCat09** [comment]
@siroo2137, @reka7490,
could you check this feature?

**Comment by reka7490** [comment]
да без б

**Comment by reka7490** [comment]
Почему-то не работает всё обновил апи поставил из анти-капча и из ру-капча 
![image](https://user-images.githubusercontent.com/111941389/194327466-9a0b1721-7df2-4f00-941a-cc21a0bdc481.png)

**Comment by DarkCat09** [comment]
```python
>>> from python_aternos import Client
>>> at = Client.from_credentials('world35g', 'world35g', captcha={'api_key': 'test'})
>>> at.atconn.session.captcha
{}
```

Да, параметры почему-то не передаются в конструктор CloudScaper (в т.ч. и словарь `captcha`).  
Постараюсь исправить как можно быстрее.

***

Right, parameters is not passed to CloudScraper constructor (including `captcha` dictionary) for some unknown reason.  
I'll try to fix it as soon as possible.

**Comment by DarkCat09** [comment]
@siroo2137, @reka7490, @BABAROKA911,

**Maybe** fixed in https://github.com/DarkCat09/python-aternos/commit/092f9356a3e18dc0e08b84b695637fc59b1fdea0  
Please, update to the latest version:
```bash
pip install -U "python-aternos>=2.1.2"
```

I'm still surprised why Cloudflare allows me send requests from my devices and even from Replit.

***

**Возможно**, пофикшено в коммите https://github.com/DarkCat09/python-aternos/commit/092f9356a3e18dc0e08b84b695637fc59b1fdea0  
Обновитесь до последней версии, пожалуйста.

Меня всё ещё удивляет, что Клаудфлэр пропускает запросы с моих устройств (даже с Replit-а).

**Comment by DarkCat09** [comment]
From `v3.0.0`, any arguments to CloudScraper are passed this way:
```python
from python_aternos import Client

at = Client()

at.atconn.session.captcha = {
    'provider': '2captcha',
    'api_key': 'your_api_key',
}

at.login('username', 'password')
```

**Comment by Aeron-Emory** [comment]
> ```shell
> python-aternos
> ```

I have added in that bit, I still get 
cloudscraper.exceptions.CloudflareChallengeError: Detected a Cloudflare version 2 Captcha challenge, This feature is not available in the opensource (free) version.
Do I need to install in development mode while changing those lines?

**Comment by Aeron-Emory** [comment]
Okay, so I have dug a bit deeper trying to get 2captcha to work, according to the Cloudflare turnstile [documentation](https://developers.cloudflare.com/turnstile/get-started/client-side-rendering/), I need the sitekey and turnstile can be loaded 2 ways:
**Implicitly render the Turnstile widget**
So, basically, it is the easiest to solve as the sitekey is loaded in the HTML sort of like this:
```html
<div class="cf-turnstile" data-sitekey="yourSitekey" data-callback="javascriptCallback"></div>
```
**Explicitly render the Turnstile widget**
This one here is the problem, as it is much harder to solve, it has the sitekey on a javascript that you must intercept to get the sitekey, and unfortunately, Aternos uses this method.
Here is the place where the sitekey is stored.
```js
window.onloadTurnstileCallback = function () {
    turnstile.render('#example-container', {
        sitekey: '<YOUR_SITE_KEY>',
        callback: function(token) {
            console.log(`Challenge Success ${token}`);
        },
    });
};
```

So, as per the 2captcha [documentation](https://2captcha.com/2captcha-api#turnstile) I tried intercepting
```py
# Inject JavaScript code to intercept turnstile.render() arguments
script = """
const i = setInterval(()=>{
  if (window.turnstile) {
    clearInterval(i)
    window.turnstile.render = (a,b) => {
      console.log(b)
      return 'foo'
    }
  }
},50)
"""
browser.execute_script(script)

# Wait for the JavaScript code to execute
time.sleep(5)

# Retrieve the browser's log entries
logs = browser.get_log("browser")
for log in logs:
    print(log["message"])
```
But ultimately, this failed as well, seems like aternos has some sort of system in place that can detect when such attempts are made and refuse to connect with the 403 response...
I don't know where to go from here

**Comment by DarkCat09** [comment]
@Aeron-Emory, please, read https://github.com/DarkCat09/python-aternos/issues/62#issuecomment-1613585386  
I'll notify about any updates in the issue 62.  
Thanks a lot for your research, this could help.
